version: "3.9"

services:
  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mariadb://java_db:3306/mysql
    depends_on:
      - java_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: root
